name: "sample"

on:
  workflow_dispatch:

jobs:
  test:
    name: "test"
    runs-on:
    - "ubuntu-latest"
    container:
      image: node:16
    steps:
    - uses: "actions/checkout@v4"
    - run: "yarn install"
    - 
      run: "yarn run test:unit"
      name: "Run tests"
  cypress-run:
    name: "cypress/run"
    runs-on:
    - "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - 
      uses: "cypress-io/github-action@v6"
      with:
        command: "yarn  run test:e2e --headless"
