name: "sample"

on:
  workflow_dispatch:

jobs:
  test:
    name: "test"
    runs-on:
    - "ubuntu-latest"
    container:
      image: "cimg/node:16.16"
      options: "--user root"
    steps:
    - uses: "actions/checkout@v4"
    - run: "yarn install"
    - 
      run: "yarn run test:unit"
      name: "Run tests"
  cypress-run:
    name: "cypress/run"
    runs-on:
    - "ubuntu-latest"
    container:
      image: "cypress/browsers:node16.14.0-chrome99-ff97"
      options: "--user root"
    steps:
    - uses: "actions/checkout@v4"
    - run: "yarn  run test:e2e --headless "
